apiVersion: apps/v1
kind: Deployment
metadata:
  name: $PROJECT_NAME-deployment
  labels:
    app: $PROJECT_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $PROJECT_NAME
  template:
    metadata:
      labels:
        app: $PROJECT_NAME
    spec:
      containers:
        - name: $PROJECT_NAME
          image: $IMAGE
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: 87.106.158.45
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: mariadb-root-password
                  optional: false
            - name: DB_PORT
              value: "30810"
            - name: DB_NAME
              value: "team8"

      #     volumeMounts:
      #       - mountPath: /root/pb_data
      #         name: data-storage
      # volumes:
      #   - name: data-storage
      #     persistentVolumeClaim:
      #       claimName: $PROJECT_NAME-pvc
      restartPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson-github-com
