/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        Iqanto: {
          "orange-50": "#fdf0e7",
          "orange-100": "#f9d1b3",
          "orange-200": "#f6ba8e",
          "orange-300": "#f29b5b",
          "orange-400": "#ef873b",
          "orange-500": "#eb690a",
          "orange-600": "#d66009",
          "orange-700": "#a74b07",
          "orange-800": "#813a06",
          "orange-900": "#632c04",
          "white-50": "#fefefe",
          "white-100": "#fdfdfd",
          "white-200": "#fbfbfb",
          "white-300": "#fafafa",
          "white-400": "#f9f9f9",
          "white-500": "#f7f7f7",
          "white-600": "#e1e1e1",
          "white-700": "#afafaf",
          "white-800": "#888888",
          "white-900": "#686868",
          "grey-50": "#ececec",
          "grey-100": "#c3c3c3",
          "grey-200": "#a5a5a5",
          "grey-300": "#7c7c7c",
          "grey-400": "#636363",
          "grey-500": "#3c3c3c",
          "grey-600": "#373737",
          "grey-700": "#2b2b2b",
          "grey-800": "#212121",
          "grey-900": "#191919",
          "black-50": "#e6e6e6",
          "black-100": "#b0b0b0",
          "black-200": "#8a8a8a",
          "black-300": "#545454",
          "black-400": "#333333",
          "black-500": "#000000",
          "black-600": "#000000",
          "black-700": "#000000",
          "black-800": "#000000",
          "black-900": "#000000",
        },

        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
